Drink.create([
  {name: "Old Fashioned", description: "The Old Fashioned is a cocktail made by muddling sugar with bitters, then adding alcohol, such as whiskey or brandy, and a twist of citrus rind. It is traditionally served in a short, round, 812 US fl oz (240350 ml) tumbler-like glass, which is called an Old Fashioned glass, named after the drink.\n\nThe Old Fashioned, developed during the 19th century and given its name in the 1880s, is an IBA Official Cocktail. It is also one of six basic drinks listed in David A. Embury's The Fine Art of Mixing Drinks.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912757/Whiskey_Old_Fashioned1_ox0xdc.jpg"},
  {name: "Negroni", description: "The Negroni cocktail is made of one part gin, one part vermouth rosso (red, semi-sweet), and one part Campari, garnished with orange peel. It is considered an aperitif.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912750/Negroni_served_in_Vancouver_BC_izhahr.jpg"},
  {name: "Mojito", description: "Traditionally, a mojito is a cocktail that consists of five ingredients: white rum, sugar (traditionally sugar cane juice), lime juice, sparkling water, and mint. The original Cuban recipe uses spearmint or yerba buena, a mint variety very popular on the island. Its combination of sweetness, refreshing citrus, and mint flavors is intended to complement the potent kick of the rum, and has made this clear highball a popular summer drink. The cocktail has a relatively low alcohol content (about 10 percent alcohol by volume).", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912741/15-09-26-RalfR-WLC-0067_k5njso.jpg"},
  {name: "Margarita", description: "The margarita is a cocktail consisting of tequila, triple sec and lime or lemon juice, often served with salt on the rim of the glass. The drink is served shaken with ice (on the rocks), blended with ice (frozen margarita), or without ice (straight up). Although it has become acceptable to serve a margarita in a wide variety of glass types, ranging from cocktail and wine glasses to pint glasses and even large schooners, the drink is traditionally served in the eponymous margarita glass, a stepped-diameter variant of a cocktail glass or champagne coupe.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912734/MargaritaReal_n7yoqz.jpg"},
  {name: "Sazerac", description: "The Sazerac is a local New Orleans variation of a Cognac or whiskey cocktail, named for the Sazerac de Forge et Fils brand of Cognac brandy that served as its original main ingredient. The drink is most traditionally a combination of Cognac or rye, absinthe, Peychaud's Bitters, and sugar, although bourbon whiskey or Herbsaint are sometimes substituted. Some claim it is the oldest known American cocktail, with origins in pre–Civil War New Orleans, although drink historian David Wondrich is among those who dispute this, and American instances of published usage of the word cocktail to describe a mixture of spirits, bitters, and sugar can be traced to the dawn of the 19th century.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912723/SazeracRooseveltNOLA1July2009_bjtks6.jpg"},
  {name: "Clover Club", description: "The Clover Club Cocktail is a cocktail consisting of Gin, Lemon Juice, Raspberry Syrup, and an egg white. The egg white is not added for the purpose of giving the drink flavor, but rather acts as an emulsifier. Thus when the drink is shaken a characteristic foamy head is formed.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912708/Cloverclub_ld76mw.jpg"},
  {name: "Martini", description: "The Martini is a cocktail made with gin and vermouth, and garnished with an olive or a lemon twist. Over the years, the Martini has become one of the best-known mixed alcoholic beverages. H. L. Mencken called the Martini \"the only American invention as perfect as the sonnet\" and E. B. White called it \"the elixir of quietude\".", image_url: "http://res.cloudinary.com/distillr/image/upload/v1467912696/15-09-26-RalfR-WLC-0084_ernvpz.jpg"},
  {name: "Manhattan", description: "A Manhattan is a cocktail made with whiskey, sweet vermouth, and bitters. Commonly used whiskeys include rye (the traditional choice), Canadian whisky, bourbon, blended whiskey, and Tennessee whiskey. The cocktail is often stirred and strained into a cocktail glass, where it is garnished with a Maraschino cherry with a stem. A Manhattan can also be served on the rocks in a lowball glass. ", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467766560/scvdxllckzbufzbkxal7.jpg"},
  {name: "Absinthe", description: "Absinthe is historically described as a distilled, highly alcoholic (45–74% ABV / 90–148 U.S. proof) beverage. It is an anise-flavoured spirit derived from botanicals, including the flowers and leaves of Artemisia absinthium (\"grand wormwood\"), together with green anise, sweet fennel, and other medicinal and culinary herbs. Absinthe traditionally has a natural green colour but may also be colourless. It is commonly referred to in historical literature as \"la fée verte\" (the green fairy). Although it is sometimes mistakenly referred to as a liqueur, absinthe is not traditionally bottled with added sugar; it is therefore classified as a spirit. Absinthe is traditionally bottled at a high level of alcohol by volume, but it is normally diluted with water prior to being consumed.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911082/ji2bocmi69etrwtmycxj.jpg"},
  {name: "Brandy Alexander", description: "A Brandy Alexander is a brandy-based cocktail consisting of cognac and crème de cacao that became popular during the early 20th century. It is a variation of an earlier, gin-based cocktail called simply an Alexander.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911154/sqnnxsomvy9ebenzftxi.jpg"},
  {name: "Jack Rose", description: "A Jack Rose is a cocktail containing applejack, grenadine, and lemon or lime juice. It was popular in the 1920s and 1930s, notably appearing in Ernest Hemingway's 1926 classic, The Sun Also Rises, in which Jake Barnes, the narrator, drinks a Jack Rose in the Crillon Paris hotel bar while awaiting the arrival of Lady Brett Ashley. It was also a favorite drink of author John Steinbeck.\n\nThe Jack Rose is one of six basic drinks listed in David A. Embury's The Fine Art of Mixing Drinks.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911197/ykqa4bsig51oy7wkrqkd.jpg"},
  {name: "Pisco Sour", description: "A pisco sour is a cocktail typical of South American cuisine. The drink's name comes from pisco, which is its base liquor, and the cocktail term sour, in reference to sour citrus juice and sweetener components. The Peruvian pisco sour uses Peruvian pisco as the base liquor and adds Key lime (or lemon) juice, syrup, ice, egg white, and Angostura bitters. The Chilean version is similar, but uses Chilean pisco and pica lime, and excludes the bitters and egg white. Other variants of the cocktail include those created with fruits like pineapple or plants such as coca leaves.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911237/fyoqkflteekatcyfvvha.jpg"},
  {name: "Sidecar", description: "The sidecar is a cocktail traditionally made with cognac, orange liqueur (Cointreau, Grand Marnier, Grand Gala or another triple sec), and lemon juice. In its ingredients, the drink is perhaps most closely related to the older brandy crusta, which differs both in presentation and in proportions of its components.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911260/wuaueijspnxpchhjuykm.jpg"},
  {name: "Stinger", description: "A stinger is a Duo cocktail made by adding crème de menthe to a spirit.\n\nThe classic recipe is based on brandy and white crème de menthe, shaken and served in a cocktail glass. The origins of this drink are unclear, but it is mentioned in bartender's recipe books as far back as Tom Bullock's The Ideal Bartender, published in 1917.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911290/syxweyopr9ywd6t2rxvw.jpg"},
  {name: "Aviation", description: "The Aviation is a classic cocktail made with gin, maraschino liqueur, crème de violette, and lemon juice. Some recipes omit the crème de violette. It is served straight up, in a cocktail glass.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911317/yi51m2i9rxa45bjxnahk.jpg"},
  {name: "French 75", description: "French 75 is a cocktail made from gin, Champagne, lemon juice, and sugar. It is also called a 75 Cocktail, or in French simply a Soixante Quinze (Seventy Five).\n\nThe drink dates to World War I, and an early form was created in 1915 at the New York Bar in Paris—later Harry's New York Bar—by barman Harry MacElhone. The combination was said to have such a kick that it felt like being shelled with the powerful French 75mm field gun.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911341/klqaowpmnbfzotwhbqna.jpg"},
  {name: "Gimlet", description: "The gimlet is a cocktail made of gin and lime juice. A 1928 description of the drink was: \"gin, a spot of lime, and soda.\" The description in the 1953 Raymond Chandler novel The Long Goodbye stated that \"a real gimlet is half gin and half Rose's lime juice and nothing else\". The derivation of the naming of the gimlet cocktail has caused a little confusion. Surgeon General Sir Thomas Gimelette, (RN 1879-1913), first added lime cordial to the daily gin tot of the men of the Royal Navy under his care to help combat the ravages of scurvy on long voyages. Scurvy was a common ailment of the ordinary seamen of the navy due to a lack of vitamin C while on long voyages without fresh supplies of fruit and vegetables. The gimlet was named after the Surgeon General.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911376/htwt0w92kyt9jmxaesgz.jpg"},
  {name: "Gin and Tonic", description: "A gin and tonic is a highball cocktail made with gin and tonic water poured over ice. It is usually garnished with a slice or wedge of lime. The amount of gin varies according to taste. Suggested ratios of gin to tonic are 1:1, 1:2, 1:3, and 2:3.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911404/hfasr6ssmwo8i75ynpqz.jpg"},
  {name: "Rickey", description: "The Rickey is a highball drink made from gin or bourbon, half of a lime squeezed and dropped in the glass, and carbonated water. Little or no sugar is added to the rickey. Originally created with bourbon in Washington, D.C. at Shoomaker's bar by bartender George A. Williamson in the 1880s, purportedly in collaboration with Democratic lobbyist Colonel Joe Rickey, it became a worldwide sensation when mixed with gin a decade later.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911434/oabczdwl4wyhjxwlaon1.jpg"},
  {name: "Long Island Iced Tea", description: "A Long Island Iced Tea is a type of alcoholic mixed drink typically made with tequila, vodka, light rum, triple sec, gin, and a splash of cola, which gives the drink the same amber hue as its namesake. It is so named because of the resemblance to the color and taste of iced tea. A popular version mixes equal parts vodka, gin, tequila, rum, and triple sec with 1½ parts sour mix and a splash of cola.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911460/atw1a0evmycfrcqrb3sv.jpg"},
  {name: "Pink Lady", description: "The Pink Lady is a classic gin-based cocktail with a long history. Its pink color is due to adding grenadine.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911491/bubq9bsan0wbvj3cwwv2.jpg"},
  {name: "Ramos Fizz", description: "A Ramos gin fizz (also known as a \"Ramos fizz\" or \"New Orleans fizz\") contains gin, lemon juice, lime juice, egg white, sugar, cream, orange flower water, and soda water. It is served in a large non-tapered 12 to 14 ounce Collins glass.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911517/gkimej7ne567hxwjpjk1.jpg"},
  {name: "Tom Collins", description: "The Tom Collins is a Collins cocktail made from gin, lemon juice, sugar, and carbonated water. First memorialized in writing in 1876 by Jerry Thomas, \"the father of American mixology\", this \"gin and sparkling lemonade\" drink is typically served in a Collins glass over ice.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911547/qp3tnwmqjhp10qhgimbr.jpg"},
  {name: "Cuba Libre", description: "The Cuba Libre is a cocktail made of cola, lime, and dark or light rum. This cocktail is often referred to as a Rum and Coke in the United States, Canada, the UK, Ireland, Australia and New Zealand where the lime juice may or may not be included.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911577/ujvtunndsakfsgrqwrpw.jpg"},
  {name: "Daiquiri", description: "Daiquiri is a family of cocktails whose main ingredients are rum, citrus juice (typically lime juice), and sugar or other sweetener.\n\nThe daiquiri is one of the six basic drinks listed in David A. Embury's classic The Fine Art of Mixing Drinks. In the book, he also suggests some variations.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911634/b2ug02brtnei7hy5ajiz.jpg"},
  {name: "Dark N Stormy", description: "A Dark 'N' Stormy is a highball cocktail made with dark rum (the dark) and ginger beer (the stormy) served over ice and garnished with a slice of lime. In the US, the name \"Dark 'N Stormy\" is a trademark of Gosling Brothers Ltd of Bermuda. Gosling's claims there is only one recipe for a Dark 'N Stormy, but the NY Times reports that Gosling's has changed that recipe along with changing commercial relationships; Gosling's recipe does call for Gosling's Black Seal Rum.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911674/vacjpr4ruxhszk5vsgok.jpg"},
  {name: "El Presidente", description: "The El Presidente is a mix of rum, curaçao, vermouth, and grenadine.\n", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911696/deoh6004i3dt9nwslj0b.jpg"},
  {name: "Mai Tai", description: "The Mai Tai is an alcoholic cocktail based on rum, Curaçao liqueur, and lime juice, associated with Polynesian-style settings.\n\n\"Maita'i\" is the Tahitian word for \"good\"; but the drink is spelled as two words, sometimes hyphenated or capitalized.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911726/rzt7zurgyasmqpscv7ft.jpg"},
  {name: "Piña Colada", description: "The piña colada is a sweet cocktail made with rum, coconut cream or coconut milk, and pineapple juice, usually served either blended or shaken with ice. It may be garnished with either a pineapple wedge, a maraschino cherry, or both. The piña colada has been the national drink of Puerto Rico since 1978.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911770/bccydb4norh7quatpvwg.jpg"},
  {name: "Planter's Punch", description: "Planter's Punch is an IBA Official Cocktail made of dark rum, several juices, grenadine syrup, sugar syrup, and Angostura bitters.\n\nThe cocktail has been said to have originated at the Planters Hotel in Charleston, SC, but the recipe originates in Jamaica.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911800/blfxf1q2oyxkqqmtz7yt.jpg"},
  {name: "Paloma", description: "The paloma (Spanish for \"dove\") is a tequila-based cocktail. This drink is most commonly prepared by mixing tequila with a grapefruit-flavored soda such as Fresca, Squirt, or Jarritos and served on the rocks with a lime wedge. This drink also has the option of adding salt to the rim of the glass.\n\nAlternatively, the grapefruit soda can be replaced with fresh white or red grapefruit juice (jugo de toronja), club soda (sugar optional), and fresh-squeezed lime juice.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911870/pmdwdyzivvgubjq4vo3b.jpg"},
  {name: "Tequila Sunrise", description: "The Tequila Sunrise is a cocktail made of tequila, orange juice, and grenadine syrup and served unmixed in a tall glass . The modern drink originates from Sausalito in the early 1970s, after an earlier one created in the 1930s in Phoenix, near Scottsdale. The cocktail is named for its appearance when served, with gradations of color resembling a sunrise.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911961/bcm1xcij58rqz9lwzazs.jpg"},
  {name: "Cosmopolitan", description: "A cosmopolitan, or informally a cosmo, is a cocktail made with vodka, triple sec, cranberry juice, and freshly squeezed or sweetened lime juice.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467911980/d8sqeuamsnv2tv9dkxwi.jpg"},
  {name: "Kamikaze", description: "The Kamikaze is made of equal parts vodka, triple sec and lime juice. According to the International Bartenders Association, it is served straight up in a cocktail glass. Garnish is typically a wedge or twist of lime.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912001/s4rgs8iv7vuhasmtwiau.jpg"},
  {name: "Lemon Drop", description: "A Lemon Drop is a vodka-based cocktail that has a lemony, sweet and sour flavor, prepared using lemon juice, triple sec and simple syrup. It has been described as a variant of, or as \"a take on\", the Vodka Martini. It is typically prepared and served straight up – chilled with ice and strained.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912028/m3jni18zvas27o5bh2xx.jpg"},
  {name: "Moscow Mule", description: "A Moscow Mule, also known as a Vodka buck, is a cocktail made with a high-quality vodka, a spicy ginger beer, and lime juice, garnished with a slice or wedge of lime. It is usually served in a copper mug.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912050/uzgxz8igshb0iajp9wrb.jpg"},
  {name: "Screwdriver", description: "A screwdriver is a popular alcoholic highball drink made with orange juice and vodka. While the basic drink is simply the two ingredients, there are many variations; the most common one is made with one part vodka, one part of any kind of orange soda, and one part of orange juice. Many of the variations have different names in different parts of the world. The International Bartender Association has designated this cocktail as an IBA Official Cocktail.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912070/t3rxhcoyhdsltf2tlnux.jpg"},
  {name: "Vesper", description: "The Vesper or Vesper Martini is a cocktail that was originally made of gin, vodka, and Kina Lillet.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912103/mkqzxhesgm60zxdbpim4.jpg"},
  {name: "White Russian", description: "A White Russian is a cocktail made with vodka, coffee liqueur (e.g., Kahlúa or Tia Maria), and cream served with ice in an Old Fashioned glass. Often milk will be used as an alternative to cream.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912125/drlpqgubnrpys65io9m7.jpg"},
  {name: "Mint Julep", description: "The mint julep is a mixed alcoholic drink, or cocktail, consisting primarily of bourbon (or some other spirit), water, crushed or shaved ice, and fresh mint. As a bourbon-based cocktail, it is associated with the American South and the cuisine of the Southern United States in general, and the Kentucky Derby in particular.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912145/nfpdsyc2iyn6hdqdiygz.jpg"},
  {name: "Rob Roy", description: "The Rob Roy is a cocktail created in 1894 by a bartender at the Waldorf Astoria in Manhattan, New York City. The drink was named in honor of the premiere of Rob Roy, an operetta by composer Reginald De Koven and lyricist Harry B. Smith loosely based upon Scottish folk hero Rob Roy MacGregor.\n\nA Rob Roy is similar to a Manhattan but is made exclusively with Scotch whisky, while the Manhattan is traditionally made with rye and today commonly made with bourbon or Canadian whisky.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912179/csuou1urxgvanusdaqgk.jpg"},
  {name: "Whiskey Sour", description: "The whiskey sour is a mixed drink containing whiskey (often bourbon), lemon juice, sugar, and optionally, a dash of egg white. With the egg white, it is sometimes called a Boston Sour. For those who do not like or cannot have egg white (e.g., due to religious concerns or allergy to eggs), pineapple juice is used as a substitute. It is shaken and served either straight up or over ice.\n\nThe traditional garnish is half an orange slice and a maraschino cherry.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912206/gb111zcpsdzulbqqczpg.jpg"},
  {name: "Ward Eight", description: "The Ward 8 or Ward Eight is a cocktail originating in 1898 in Boston, Massachusetts at the bar of the Gilded Age restaurant Locke-Ober.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912230/ozz1onzi9cqklny4qcm5.jpg"},
  {name: "Mimosa", description: "A Mimosa is a cocktail composed of equal parts champagne (or other sparkling wine) and chilled citrus fruit juice, usually orange juice unless otherwise specified (e.g. a grapefruit juice mimosa). It is traditionally served in a tall champagne flute with a morning brunch, to guests at weddings, or as part of \"1st Class\" service on some passenger railways and airlines.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912249/z7t1w2hygweqt2p47gcn.jpg"},
  {name: "Grasshopper", description: "A grasshopper is a sweet, mint-flavored, after-dinner drink. The name of the drink derives from its green color, which comes from crème de menthe. The drink reputedly originated at Tujague's, a landmark bar in the French Quarter of New Orleans, Louisiana, and was invented by its owner, Philip Guichet. The drink gained popularity during the 1950s and 1960s throughout the American South.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912272/bgucg4qilzmn84iutpmd.jpg"},
  {name: "Harvey Wallbanger", description: "The Harvey Wallbanger is a mixed drink made with vodka, Galliano, and orange juice.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912302/zfevqmuj2u2lqmsry9sc.jpg"},
  {name: "Boulevardier", description: "The boulevardier cocktail is an alcoholic drink composed of bourbon, sweet vermouth, and campari. Its creation is ascribed to Erskine Gwynne, an American-born writer who founded a monthly magazine in Paris called Boulevardier, which appeared from 1927 to 1932.\n\nThe boulevardier is similar to a Negroni, sharing two of its three ingredients. It is differentiated by its use of bourbon whiskey or rye whiskey as its principal component instead of gin.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912364/keniyc9qrp5y8lcraq1m.jpg"},
  {name: "White Lion", description: "White Lion\n• 1 tsp Sugar\n• 1 oz Lemon Juice\n• 1 1/2 oz Rum\n• 1/4 oz Grenadine or Falernum\n• 2 dash Bitters\nShake with ice and strain into a cocktail glass. Variation: serve in a Highball glass with crushed ice and soda water. Orange curaçao may be added.", image_url: "https://res.cloudinary.com/distillr/image/upload/v1467912531/sptu66c9jlko1c83eqfm.jpg"}
])
User.create([
  {username: "Ari", password: "Nutmeg"},
  {username: "karamisaurus", password: "karamisaurus"},
  {username: "Guest", password: "password"},
  {username: "Ashara", password: "Ashara"},
  {username: "Rynsia", password: "Rynsia"},
  {username: "Kara", password: "password"},
  {username: "Relina", password: "password"},
  {username: "Cecil", password: "password"},
  {username: "Chia", password: "password"},
  {username: "Abelardo", password: "password"},
  {username: "Laurence", password: "password"},
  {username: "Graham", password: "password"},
  {username: "Marielle", password: "password"},
  {username: "Carli", password: "password"},
  {username: "Kyra", password: "password"},
  {username: "Bert", password: "password"},
  {username: "Harrison", password: "password"},
  {username: "Selina", password: "password"},
  {username: "Albertha", password: "password"},
  {username: "Liliana", password: "password"}
])
Checkin.create([
  {user_id: 2, drink_id: 1, rating: 4, review: "", venue_id: 1},
  {user_id: 2, drink_id: 5, rating: 5, review: "", venue_id: 2},
  {user_id: 2, drink_id: 7, rating: 4, review: "", venue_id: 4},
  {user_id: 3, drink_id: 43, rating: 3, review: "", venue_id: 6},
  {user_id: 3, drink_id: 45, rating: 2, review: "Not enough cream.", venue_id: 20},
  {user_id: 8, drink_id: 47, rating: 3, review: "Suitable", venue_id: 3},
  {user_id: 9, drink_id: 48, rating: 5, review: "Really good!!", venue_id: 0},
  {user_id: 10, drink_id: 12, rating: 2, review: "meh", venue_id: 10},
  {user_id: 12, drink_id: 1, rating: 5, review: "Tasty!", venue_id: 6},
  {user_id: 13, drink_id: 22, rating: 3, review: "nice", venue_id: 0},
  {user_id: 14, drink_id: 15, rating: 4, review: "", venue_id: 0},
  {user_id: 15, drink_id: 26, rating: 1, review: "Could barely taste the ginger", venue_id: 8},
  {user_id: 16, drink_id: 29, rating: 3, review: "mmm", venue_id: 0},
  {user_id: 17, drink_id: 45, rating: 5, review: "yes!!!", venue_id: 0},
  {user_id: 18, drink_id: 7, rating: 3, review: "It's so hard to find an excellent martini", venue_id: 0},
  {user_id: 18, drink_id: 16, rating: 4, review: "Light and refreshing", venue_id: 0},
  {user_id: 18, drink_id: 21, rating: 2, review: "Something was off", venue_id: 13},
  {user_id: 19, drink_id: 14, rating: 4, review: "", venue_id: 6},
  {user_id: 19, drink_id: 4, rating: 5, review: "", venue_id: 24},
  {user_id: 20, drink_id: 22, rating: 5, review: "My favorite!", venue_id: 0},
  {user_id: 20, drink_id: 17, rating: 2, review: "too watery :(", venue_id: 0},
  {user_id: 3, drink_id: 2, rating: 3, review: "", venue_id: 0},
  {user_id: 3, drink_id: 5, rating: 4, review: "They make it so well here", venue_id: 16},
  {user_id: 3, drink_id: 11, rating: 2, review: "", venue_id: 41}
])
Comment.create([
  {user_id: 3, checkin_id: 3, comment: "Nice!"},
  {user_id: 3, checkin_id: 5, comment: "Mint was good, though."},
  {user_id: 12, checkin_id: 4, comment: "Try their old fashioned"},
  {user_id: 17, checkin_id: 5, comment: "I love grasshoppers!!!"},
  {user_id: 3, checkin_id: 21, comment: "I hate that!"}
])
Friend.create([
  {user_id: 2, friend_id: 3, status: "accepted"},
  {user_id: 3, friend_id: 2, status: "accepted"},
  {user_id: 3, friend_id: 1, status: "accepted"},
  {user_id: 1, friend_id: 3, status: "accepted"},
  {user_id: 1, friend_id: 2, status: "pending"},
  {user_id: 3, friend_id: 4, status: "accepted"},
  {user_id: 4, friend_id: 3, status: "accepted"},
  {user_id: 4, friend_id: 5, status: "accepted"},
  {user_id: 5, friend_id: 4, status: "accepted"},
  {user_id: 6, friend_id: 3, status: "pending"},
  {user_id: 7, friend_id: 6, status: "pending"},
  {user_id: 3, friend_id: 8, status: "accepted"},
  {user_id: 8, friend_id: 3, status: "accepted"},
  {user_id: 1, friend_id: 9, status: "accepted"},
  {user_id: 9, friend_id: 1, status: "accepted"},
  {user_id: 7, friend_id: 9, status: "accepted"},
  {user_id: 9, friend_id: 7, status: "accepted"},
  {user_id: 3, friend_id: 10, status: "accepted"},
  {user_id: 10, friend_id: 3, status: "accepted"},
  {user_id: 1, friend_id: 11, status: "accepted"},
  {user_id: 11, friend_id: 1, status: "accepted"},
  {user_id: 3, friend_id: 12, status: "accepted"},
  {user_id: 12, friend_id: 3, status: "accepted"},
  {user_id: 7, friend_id: 12, status: "accepted"},
  {user_id: 12, friend_id: 7, status: "accepted"},
  {user_id: 7, friend_id: 13, status: "accepted"},
  {user_id: 13, friend_id: 7, status: "accepted"},
  {user_id: 11, friend_id: 14, status: "accepted"},
  {user_id: 14, friend_id: 11, status: "accepted"},
  {user_id: 11, friend_id: 15, status: "accepted"},
  {user_id: 15, friend_id: 11, status: "accepted"},
  {user_id: 11, friend_id: 16, status: "accepted"},
  {user_id: 16, friend_id: 11, status: "accepted"},
  {user_id: 3, friend_id: 17, status: "accepted"},
  {user_id: 17, friend_id: 3, status: "accepted"},
  {user_id: 18, friend_id: 3, status: "pending"},
  {user_id: 3, friend_id: 20, status: "accepted"},
  {user_id: 20, friend_id: 3, status: "accepted"}
])
Like.create!([
  {user_id: 3, checkin_id: 3},
  {user_id: 3, checkin_id: 2},
  {user_id: 12, checkin_id: 5},
  {user_id: 12, checkin_id: 4},
  {user_id: 13, checkin_id: 10},
  {user_id: 17, checkin_id: 5},
  {user_id: 3, checkin_id: 9},
  {user_id: 3, checkin_id: 20}
])
Venue.create([
  {name: "Tradition", description: "From its main bar to reservation-only snugs, this hip venue delivers handcrafted American cocktails.", address: "441 Jones St, San Francisco, CA 94102", latitude: 37.7855303, longitude: -122.4132072},
  {name: "Bourbon and Branch", description: "Reservations are required at this swanky, dimly lit unmarked bar known for handcrafted cocktails.", address: "501 Jones St, San Francisco, CA 94102", latitude: 37.7858891, longitude: -122.4131245},
  {name: "Whitechapel", description: "Gin-focused cocktail lounge with globally inspired eats in expansive, ornate, Victorian-themed digs.", address: "600 Polk St, San Francisco, CA 94102, USA", latitude: 37.782414, longitude: -122.418765},
  {name: "Smuggler's Cove", description: "Popular, kitschy bar boasting pirate-themed decor, exotic cocktails & over 200 types of rum.", address: "650 Gough St, San Francisco, CA 94102, USA", latitude: 37.7794647, longitude: -122.4233429},
  {name: "Rickhouse", description: "An after-work crowd packs this hip space highlighted by a huge menu of whiskeys & inventive drinks.", address: "246 Kearny St, San Francisco, CA 94108, USA", latitude: 37.7904993, longitude: -122.4038395},
  {name: "Bear Vs Bull", description: "Craft beer, wine & cocktails in restored art deco quarters tucked inside a stylish movie house.", address: "2550 Mission St, San Francisco, CA 94110, USA", latitude: 37.7562163, longitude: -122.4191911},
  {name: "Benjamin Cooper", description: "In the Hotel G, this cocktail bar boasts a vintage feel, creative drinks & dinner entrees.", address: "398 Geary St, San Francisco, CA 94102, USA", latitude: 37.7873662, longitude: -122.409671},
  {name: "Forgery", description: "Bar for cocktails, wine & beer in a bi-level, brick-walled space with modern lights & a casual vibe.", address: "1525 Mission St, San Francisco, CA 94103, USA", latitude: 37.7737843, longitude: -122.4175169},
  {name: "Laszlo", description: "Cocktails, DJs & movie screenings featured at a cool bar connected to the restaurant Foreign Cinema.", address: "2526 Mission St, San Francisco, CA 94110, USA", latitude: 37.7565048, longitude: -122.4191014},
  {name: "The Treasury", description: "Posh cocktail lounge with a dramatic interior serving elevated drinks & New American nibbles.", address: "200 Bush St, San Francisco, CA 94104, USA", latitude: 37.7912937, longitude: -122.4010389},
  {name: "Wildhawk", description: "Dark & dramatic lounge for elevated cocktails offered in a space with high style & vintage accents.", address: "3464 19th St, San Francisco, CA 94110, USA", latitude: 37.7604248, longitude: -122.420896},
  {name: "15 Romolo", description: "Back-alley oasis teaming drinks, bar bites & a cocktail brunch with a jukebox & a sultry vibe.", address: "15 Romolo Pl, San Francisco, CA 94133, USA", latitude: 37.7981672, longitude: -122.4063811},
  {name: "ABV", description: "A large-scale mural sets the stage at this trendy spot for cocktails, beer & wine plus upscale eats.", address: "3174 16th St, San Francisco, CA 94103, USA", latitude: 37.7650455, longitude: -122.4235778},
  {name: "The Alembic", description: "Classic handcrafted cocktails & an inventive bar food menu in a dimly lit, rustic space with booths.", address: "1725 Haight St, San Francisco, CA 94117, USA", latitude: 37.7693221, longitude: -122.4511197},
  {name: "Bar Agricole", description: "Sleek, contemporary dining room & patio for inspired Californian cuisine & creative cocktails.", address: "355 11th St, San Francisco, CA 94103, USA", latitude: 37.7715307, longitude: -122.4128563},
  {name: "Comstock Saloon", description: "Fancy, turn-of-the-century digs house vintage cocktails, upscale bar fare, cozy booths & live jazz.", address: "155 Columbus Ave, San Francisco, CA 94133, USA", latitude: 37.7969383, longitude: -122.405655},
  {name: "The Interval at Long Now", description: "Coffee shop, bar & event space boasting a modern setting complete with views & a librarylike vibe.", address: "2 Marina Blvd, San Francisco, CA 94123, USA", latitude: 37.806817, longitude: -122.4318391},
  {name: "Trick Dog", description: "Trendy hangout in a converted warehouse with an array of craft cocktails & eclectic small plates.", address: "3010 20th St, San Francisco, CA 94110, USA", latitude: 37.7593496, longitude: -122.4112081},
  {name: "Trou Normand", description: "Go-to eatery & lounge with marble bar serving New American bites, cocktails & namesake brandys.", address: "140 New Montgomery St, San Francisco, CA 94105, USA", latitude: 37.7866839, longitude: -122.3998832},
  {name: "Alchemist Bar & Lounge", description: "Dim, trendy cocktail bar with steampunk decor prepares signature drinks with housemade ingredients.", address: "679 3rd St, San Francisco, CA 94107, USA", latitude: 37.7795005, longitude: -122.393038},
  {name: "Maven", description: "Small plates & creative drinks in a modern setting with wall-mounted plants & polished log tables.", address: "598 Haight St, San Francisco, CA 94117, USA", latitude: 37.7721798, longitude: -122.4320123},
  {name: "Bergerac", description: "Global eats & craft cocktails served in bohemian digs with bar, varied seating & vintage furniture.", address: "316 11th St, San Francisco, CA 94103, USA", latitude: 37.7713824, longitude: -122.4138309},
  {name: "The Devil's Acre", description: "Throwback tavern & basement bar (Remedie) for apothecary-themed cocktails. Reservations recommended.", address: "256 Columbus Ave, San Francisco, CA 94133, USA", latitude: 37.7976889, longitude: -122.406135},
  {name: "Novela", description: "A stylish, literary-themed bar with drinks named after characters, punch on tap & book-lined walls.", address: "662 Mission St, San Francisco, CA 94105, USA", latitude: 37.7870969, longitude: -122.4013597},
  {name: "Bloodhound", description: "Pool tables & a signature cocktail list in a rustic setting resembling a hunting lodge.", address: "1145 Folsom St, San Francisco, CA 94103, USA", latitude: 37.7757727, longitude: -122.4087546},
  {name: "Rye", description: "Bartenders craft top-shelf cocktails at this sleek bar done up with exposed brick & polished wood.", address: "688 Geary St, San Francisco, CA 94102, USA", latitude: 37.7867628, longitude: -122.4145817},
  {name: "Beretta", description: "Handcrafted pizzas, small bites & unique cocktails keep this trendy spot hopping.", address: "1199 Valencia St, San Francisco, CA 94110, USA", latitude: 37.7538422, longitude: -122.4206999},
  {name: "Burritt Room and Tavern", description: "Hip bar inside Mystic Hotel offering specialty cocktails & extensive wine list in retro-style space.", address: "417 Stockton St, San Francisco, CA 94108, USA", latitude: 37.7897895, longitude: -122.4074167},
  {name: "83 Proof", description: "Popular watering hole serving specialty cocktails & whiskeys in a modern, loftlike space.", address: "83 1st St, San Francisco, CA 94105, USA", latitude: 37.7901622, longitude: -122.3977649},
  {name: "Zam Zam", description: "A curved bar serving classic cocktails complete with a vintage cash register, mural & jukebox.", address: "1633 Haight St, San Francisco, CA 94117, USA", latitude: 37.769531, longitude: -122.4493727},
  {name: "Absinthe Brasserie & Bar ", description: "Upscale, Parisian-style brasserie serving French-Mediterranean cuisine & creative cocktails.", address: "398 Hayes St, San Francisco, CA 94102, USA", latitude: 37.7770479, longitude: -122.4229121},
  {name: "The Cavalier", description: "Hotel Zetta's British-themed brasserie delivers gastropub bites & colonial cocktails in clubby digs.", address: "360 Jessie St, San Francisco, CA 94103, USA", latitude: 37.7833359, longitude: -122.4069933},
  {name: "Elixir", description: "On a saloon site said to date back to 1858, this bar stays current with the likes of organic drinks.", address: "3200 16th St, San Francisco, CA 94103, USA", latitude: 37.7649877, longitude: -122.424332},
  {name: "Hard Water", description: "Waterfront restaurant & American whiskey bar specializing in New Orleans-inspired cuisine.", address: "3 Pier 7, San Francisco, CA 94105, USA", latitude: 37.797569, longitude: -122.3956572},
  {name: "The Royal Cuckoo", description: "The barkeeps spin vintage records at this dark bar with church pew seating & a throwback vibe.", address: "3202 Mission St, San Francisco, CA 94110, USA", latitude: 37.7454796, longitude: -122.4200916},
  {name: "Local Edition", description: "An extensive cocktail menu is offered at this underground lounge with a vintage newspaper theme.", address: "691 Market St, San Francisco, CA 94105", latitude: 37.7875963, longitude: -122.4031194},
  {name: "Pagan Idol", description: "Island-inspired cocktails poured in playful quarters outfitted with tiki huts & an erupting volcano.", address: "375 Bush St, San Francisco, CA 94104, USA", latitude: 37.7907248, longitude: -122.4035919},
  {name: "Blackbird", description: "Rustic-modern bar with lounge seating for creative cocktails, craft beer, happy hours & pool.", address: "2124 Market St, San Francisco, CA 94114, USA", latitude: 37.7673192, longitude: -122.4296171},
  {name: "Lord George", description: "Seafood, shareable plates, cocktails & beer in a low-key neighborhood gastropub with polished decor.", address: "555 2nd St, San Francisco, CA 94107, USA", latitude: 37.7825386, longitude: -122.3925877},
  {name: "Spruce", description: "Posh space with rotating art serving seasonal, contemporary American fare & handcrafted cocktails.", address: "3640 Sacramento St, San Francisco, CA 94118, USA", latitude: 37.787725, longitude: -122.452758},
  {name: "Clock Bar", description: "High-end Westin St. Francis Hotel bar serving inventive cocktails & gourmet bar food.", address: "335 Powell St, San Francisco, CA 94102, USA", latitude: 37.7878279, longitude: -122.4087315}
])
